Fix: package javax.annotation does not exist
Encounter the following error when run gradlew build
...
> Task :daytrader-ee7-ejb:compileJava
...
Compiling with JDK Java compiler API.
C:\dev\git\repos\sample.daytrader7\daytrader-ee7-ejb\src\main\java\com\ibm\websphere\samples\daytrader\ejb3\DTBroker3MDB.java:18:
error: package javax.annotation does not exist
import javax.annotation.Resource;
                       ^
C:\dev\git\repos\sample.daytrader7\daytrader-ee7-ejb\src\main\java\com\ibm\websphere\samples\daytrader\ejb3\DTStreamer3MDB.java:18:
error: package javax.annotation does not exist
import javax.annotation.Resource;
                       ^
C:\dev\git\repos\sample.daytrader7\daytrader-ee7-ejb\src\main\java\com\ibm\websphere\samples\daytrader\ejb3\MarketSummarySingleton.java:22:
error: package javax.annotation does not exist
import javax.annotation.PostConstruct;
                       ^
C:\dev\git\repos\sample.daytrader7\daytrader-ee7-ejb\src\main\java\com\ibm\websphere\samples\daytrader\ejb3\TradeSLSBBean.java:25:
error: package javax.annotation does not exist
import javax.annotation.PostConstruct;
                       ^
C:\dev\git\repos\sample.daytrader7\daytrader-ee7-ejb\src\main\java\com\ibm\websphere\samples\daytrader\ejb3\TradeSLSBBean.java:26:
error: package javax.annotation does not exist
import javax.annotation.Resource;
                       ^
...